import type { Meta } from '@storybook/react';
import type Input from './input';

type ArgTypes = Meta<typeof Input>['argTypes'];

// extend the default argTypes generated by Storybook
// there is an issue with Storybook that it will not generate all the argTypes when using forwardRef
const argTypes: ArgTypes = {
  // variant: {
  //   description: 'The variant of the button',
  //   table: {
  //     defaultValue: { summary: 'default' },
  //     type: {
  //       summary: 'default | secondary | destructive | ghost | link | outline',
  //     },
  //   },
  // },
  disabled: {
    description: 'Disables the input',
    table: {
      defaultValue: { summary: 'false' },
      type: {
        summary: 'boolean',
      },
    },
  },
  placeholder: {
    description: 'Sets the placeholder text for the input',
    table: {
      type: {
        summary: 'string',
      },
    },
  },
  readOnly: {
    description: 'Makes the input read only',
    table: {
      defaultValue: { summary: 'false' },
      type: {
        summary: 'boolean',
      },
    },
  },
  onChange: {
    description:
      'Handler that is called when the element value changes. You can pull out the new value by accessing `event.target.value` (string).',
    table: {
      defaultValue: {},
      type: {
        summary: '(event: Event) => void',
      },
    },
  },
};

export default argTypes;
