import type { Meta } from '@storybook/react';
import type Label from './label';

type ArgTypes = Meta<typeof Label>['argTypes'];

// extend the default argTypes generated by Storybook
// there is an issue with Storybook that it will not generate all the argTypes when using forwardRef
const argTypes: ArgTypes = {
  htmlFor: {
    description: 'Links the label to a form element',
    table: {
      type: {
        summary: 'string',
      },
    },
  },
};

export default argTypes;
